name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install bandit codespell flake8 velin
      - run: bandit --recursive --skip B101,B110 .
      - run: codespell resampy
      - run: flake8 resampy --count --select=E9,F63,F7,F82 --show-source --statistics
      - run: python -m velin --check resampy
